"""add user to tasks

Revision ID: b35e4046c0af
Revises: 1dc7fd679488
Create Date: 2026-07-28 12:49:23.334842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b35e4046c0af'
down_revision: Union[str, Sequence[str], None] = '1dc7fd679488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_tasks_user_id_fkey'), 'user_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'user_tasks', 'user_table', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('user_tasks_user_id_fkey'), 'user_tasks', 'user_table', ['user_id'], ['id'])
    # ### end Alembic commands ###
